name: Python Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
        
    - name: Load .env file
      uses: aarcangeli/load-dotenv@v1
      with:
        filenames: '.env'
        if-file-not-found: 'error'
        expand: 'false'
        
    - name: Run tests
      run: |
        env:
          PYTHONPATH: ${{ github.workspace }}
        pytest tests/ --cov=app --cov-report=xml 